language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - TIMEZONE="Europe/Berlin"

matrix:
  fast_finish: true
  include:
    - php: 5.4
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_install:
  - composer config --quiet github-oauth.github.com $GITHUB_TOKEN
  - composer self-update

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

before_script:
  - if [ "$TRAVIS_PHP_VERSION" = "hhv*" ]; then cat tests/fixtures/travis.ini >> /etc/hhvm/php.ini; fi;
  - if [ "$TRAVIS_PHP_VERSION" = "php*" ]; then phpenv config-add tests/fixtures/travis.ini ; fi;

script: vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - if [[ $TRAVIS_PHP_VERSION != '7.0' ]] && [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

notifications:
  email:
    - jerome@kreait.com
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/81fafa2c4f2eb03e552e

